import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
// import Navbar from "./ui/navbar";
import { inter } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Netflix Indonesia - Watch TV Shows Online, Watch Movies Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={`${inter.className} antialiased mx-auto bg-black text-white`}
      >
        {/* <div className="absolute z-40 w-full mx-auto">
          <Navbar />
        </div> */}
        <div className="relative z-0 mx-auto">

          {children}
        </div>
      </body>
    </html>
  );
}
